//
//Copyright 2012 Google Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.3
// source: test.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         string                 `protobuf:"bytes,1,opt,name=lower,proto3" json:"lower,omitempty"`                                 // to be returned upper case
	RepeatCount   int32                  `protobuf:"varint,2,opt,name=repeat_count,json=repeatCount,proto3" json:"repeat_count,omitempty"` // .. this many times
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestRequest) GetLower() string {
	if x != nil {
		return x.Lower
	}
	return ""
}

func (x *TestRequest) GetRepeatCount() int32 {
	if x != nil {
		return x.RepeatCount
	}
	return 0
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *TestResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         int64                  `protobuf:"varint,1,opt,name=items,proto3" json:"items,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Gets          int64                  `protobuf:"varint,3,opt,name=gets,proto3" json:"gets,omitempty"`
	Hits          int64                  `protobuf:"varint,4,opt,name=hits,proto3" json:"hits,omitempty"`
	Evicts        int64                  `protobuf:"varint,5,opt,name=evicts,proto3" json:"evicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *CacheStats) GetItems() int64 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *CacheStats) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *CacheStats) GetGets() int64 {
	if x != nil {
		return x.Gets
	}
	return 0
}

func (x *CacheStats) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetEvicts() int64 {
	if x != nil {
		return x.Evicts
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gets          int64                  `protobuf:"varint,1,opt,name=gets,proto3" json:"gets,omitempty"`
	CacheHits     int64                  `protobuf:"varint,12,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	Fills         int64                  `protobuf:"varint,2,opt,name=fills,proto3" json:"fills,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,3,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	MainCache     *CacheStats            `protobuf:"bytes,4,opt,name=main_cache,json=mainCache,proto3" json:"main_cache,omitempty"`
	HotCache      *CacheStats            `protobuf:"bytes,5,opt,name=hot_cache,json=hotCache,proto3" json:"hot_cache,omitempty"`
	ServerIn      int64                  `protobuf:"varint,6,opt,name=server_in,json=serverIn,proto3" json:"server_in,omitempty"`
	Loads         int64                  `protobuf:"varint,8,opt,name=loads,proto3" json:"loads,omitempty"`
	PeerLoads     int64                  `protobuf:"varint,9,opt,name=peer_loads,json=peerLoads,proto3" json:"peer_loads,omitempty"`
	PeerErrors    int64                  `protobuf:"varint,10,opt,name=peer_errors,json=peerErrors,proto3" json:"peer_errors,omitempty"`
	LocalLoads    int64                  `protobuf:"varint,11,opt,name=local_loads,json=localLoads,proto3" json:"local_loads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *StatsResponse) GetGets() int64 {
	if x != nil {
		return x.Gets
	}
	return 0
}

func (x *StatsResponse) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *StatsResponse) GetFills() int64 {
	if x != nil {
		return x.Fills
	}
	return 0
}

func (x *StatsResponse) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *StatsResponse) GetMainCache() *CacheStats {
	if x != nil {
		return x.MainCache
	}
	return nil
}

func (x *StatsResponse) GetHotCache() *CacheStats {
	if x != nil {
		return x.HotCache
	}
	return nil
}

func (x *StatsResponse) GetServerIn() int64 {
	if x != nil {
		return x.ServerIn
	}
	return 0
}

func (x *StatsResponse) GetLoads() int64 {
	if x != nil {
		return x.Loads
	}
	return 0
}

func (x *StatsResponse) GetPeerLoads() int64 {
	if x != nil {
		return x.PeerLoads
	}
	return 0
}

func (x *StatsResponse) GetPeerErrors() int64 {
	if x != nil {
		return x.PeerErrors
	}
	return 0
}

func (x *StatsResponse) GetLocalLoads() int64 {
	if x != nil {
		return x.LocalLoads
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x06testpb\"5\n" +
	"\vTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\"F\n" +
	"\vTestRequest\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\tR\x05lower\x12!\n" +
	"\frepeat_count\x18\x02 \x01(\x05R\vrepeatCount\"$\n" +
	"\fTestResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"x\n" +
	"\n" +
	"CacheStats\x12\x14\n" +
	"\x05items\x18\x01 \x01(\x03R\x05items\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x12\n" +
	"\x04gets\x18\x03 \x01(\x03R\x04gets\x12\x12\n" +
	"\x04hits\x18\x04 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06evicts\x18\x05 \x01(\x03R\x06evicts\"\xf1\x02\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04gets\x18\x01 \x01(\x03R\x04gets\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\f \x01(\x03R\tcacheHits\x12\x14\n" +
	"\x05fills\x18\x02 \x01(\x03R\x05fills\x12\x1f\n" +
	"\vtotal_alloc\x18\x03 \x01(\x04R\n" +
	"totalAlloc\x121\n" +
	"\n" +
	"main_cache\x18\x04 \x01(\v2\x12.testpb.CacheStatsR\tmainCache\x12/\n" +
	"\thot_cache\x18\x05 \x01(\v2\x12.testpb.CacheStatsR\bhotCache\x12\x1b\n" +
	"\tserver_in\x18\x06 \x01(\x03R\bserverIn\x12\x14\n" +
	"\x05loads\x18\b \x01(\x03R\x05loads\x12\x1d\n" +
	"\n" +
	"peer_loads\x18\t \x01(\x03R\tpeerLoads\x12\x1f\n" +
	"\vpeer_errors\x18\n" +
	" \x01(\x03R\n" +
	"peerErrors\x12\x1f\n" +
	"\vlocal_loads\x18\v \x01(\x03R\n" +
	"localLoads\"\a\n" +
	"\x05Empty2\xa5\x01\n" +
	"\x0eGroupCacheTest\x12+\n" +
	"\tInitPeers\x12\r.testpb.Empty\x1a\r.testpb.Empty\"\x00\x122\n" +
	"\x03Get\x12\x13.testpb.TestRequest\x1a\x14.testpb.TestResponse\"\x00\x122\n" +
	"\bGetStats\x12\r.testpb.Empty\x1a\x15.testpb.StatsResponse\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_proto_goTypes = []any{
	(*TestMessage)(nil),   // 0: testpb.TestMessage
	(*TestRequest)(nil),   // 1: testpb.TestRequest
	(*TestResponse)(nil),  // 2: testpb.TestResponse
	(*CacheStats)(nil),    // 3: testpb.CacheStats
	(*StatsResponse)(nil), // 4: testpb.StatsResponse
	(*Empty)(nil),         // 5: testpb.Empty
}
var file_test_proto_depIdxs = []int32{
	3, // 0: testpb.StatsResponse.main_cache:type_name -> testpb.CacheStats
	3, // 1: testpb.StatsResponse.hot_cache:type_name -> testpb.CacheStats
	5, // 2: testpb.GroupCacheTest.InitPeers:input_type -> testpb.Empty
	1, // 3: testpb.GroupCacheTest.Get:input_type -> testpb.TestRequest
	5, // 4: testpb.GroupCacheTest.GetStats:input_type -> testpb.Empty
	5, // 5: testpb.GroupCacheTest.InitPeers:output_type -> testpb.Empty
	2, // 6: testpb.GroupCacheTest.Get:output_type -> testpb.TestResponse
	4, // 7: testpb.GroupCacheTest.GetStats:output_type -> testpb.StatsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
